# Change these first
owner: friesipayung # Your GitHub organization or username, where this repository lives
repo: uptime-w3gg # The name of this repository


sites:
  - name: W3GG Production Web
    url: https://w3gg.io
    icon: https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://w3gg.io&size=128
  - name: W3GG Staging Web
    url: https://staging.w3gg.io
    icon: https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://w3gg.io&size=128
  - name: W3GG Production API
    method: GET
    url: https://w3gg.io/api/status
    icon: https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://w3gg.io&size=128
  - name: W3GG ICMP
    check: "tcp-ping"
    url: w3gg.io
    icon: https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://w3gg.io&size=128

status-website:
  name: W3GG
  logoUrl: https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://w3gg.io&size=128
  faviconSvg: https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://w3gg.io&size=128
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime-w3gg
  introTitle: "Status and outages of **W3GG** products."
  introMessage: ""
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - friesipayung
  - fitrul31
  - habibrosyad
  - nisaratna
      
workflowSchedule:
  graphs: "*/10 * * * *"
  responseTime: "* * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "0 * * * *"
  updates: "0 * * * *"
  uptime: "* * * * *"
